import React from 'react'


import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About",
    description: "Generated by create next app",
  };




export default function page() {
  return (
    <span className="text-7xl">
       contacto
    </span>
  )
}
